name: Release setup

on: workflow_dispatch

jobs:
  release-setup:
    if: github.repository == 'mortbopet/Ripes'
    runs-on: ubuntu-latest
    steps:

    - uses: "marvinpinto/action-automatic-releases@latest"
      if: github.ref == 'refs/heads/master'
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "continuous"
        prerelease: true
        title: "Continuous release"
